In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings(action='ignore')

In [2]:
data = pd.read_csv('전국전기차충전소_충전기_정보.csv')

In [3]:
data

,stat_nm,stat_id,chger_id,chger_type,addr,lat,lon,use_time,busi_id,busi_nm,...,chger_stat,stat_upd_dt,power_type,city_do_cd,parking_free_yn,stat_note,limit_yn,limit_detail,del_yn,del_detail
0,종묘 공영주차장,ME000001,1,3,서울특별시 종로구 종로 157,37.571076,126.995880,24시간 이용가능,ME,환경부,...,9,2.021111e+13,NaN,11,Y,NaN,N,NaN,N,NaN
1,세종로 공영주차장,ME000002,1,6,서울특별시 종로구 세종대로 189,37.573611,126.976011,24시간 이용가능,ME,환경부,...,9,2.021083e+13,NaN,11,Y,NaN,N,NaN,N,NaN
2,그랜드앰배서더 서울,ME000003,1,6,서울특별시 중구 동호로 287,37.559352,127.002350,24시간 이용가능,ME,환경부,...,9,2.021091e+13,NaN,11,N,NaN,N,NaN,N,NaN
3,한강진역 공영주차장,ME000004,1,3,서울특별시 용산구 한남동 산10-84,37.540085,127.002804,24시간 이용가능,ME,환경부,...,9,2.021091e+13,NaN,11,Y,NaN,N,NaN,N,NaN
4,기아차 성동서비스센터,ME000005,1,3,서울특별시 성동구 성수이로26길 61,37.544834,127.064226,24시간 이용가능,ME,환경부,...,9,2.021072e+13,NaN,11,N,20190626 공사로 인한 임시철거,Y,20190626 공사로 인한 임시철거,N,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89231,영남알프스복합웰컴센터,US200419,2,4,울산광역시 울주군 상북면 등억알프스리 517,35.556117,129.068415,24시간 이용가능,US,환경부,...,9,2.021113e+13,NaN,31,Y,NaN,N,NaN,N,NaN
89232,언양읍 행정복지센터,US200420,1,4,울산광역시 울주군 언양읍 동문길 7,35.569414,129.125781,24시간 이용가능,US,환경부,...,3,2.021113e+13,NaN,31,Y,NaN,N,NaN,N,NaN
89233,화봉공원 공영주차장,US200421,1,4,울산광역시 북구 화봉동 445-1,35.588995,129.364458,24시간 이용가능,US,환경부,...,3,2.021113e+13,NaN,31,Y,NaN,N,NaN,N,NaN
89234,화봉공원 공영주차장,US200421,2,4,울산광역시 북구 화봉동 445-1,35.588995,129.364458,24시간 이용가능,US,환경부,...,3,2.021113e+13,NaN,31,Y,NaN,N,NaN,N,NaN
89235,낙산해수욕장주차장,YY180001,1,6,강원도 양양군 강현면 일출로 43,38.116272,128.631878,24시간 이용가능,YY,환경부,...,9,2.019061e+13,NaN,42,Y,NaN,Y,시설 상황에 따라 이용이 제한될 수 있음,N,NaN

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89236 entries, 0 to 89235
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   stat_nm          89236 non-null  object
 1   stat_id          89236 non-null  object
 2   chger_id         89236 non-null  int64
 3   chger_type       89236 non-null  int64
 4   addr             89201 non-null  object
 5   lat              89236 non-null  float64
 6   lon              89236 non-null  float64
 7   use_time         82042 non-null  object
 8   busi_id          89236 non-null  object
 9   busi_nm          89236 non-null  object
 10  busi_call        84527 non-null  object
 11  chger_stat       89236 non-null  int64
 12  stat_upd_dt      81294 non-null  float64
 13  power_type       0 non-null      float64
 14  city_do_cd       89236 non-null  int64
 15  parking_free_yn  88793 non-null  object
 16  stat_note        13166 non-null  object
 17  limit_yn         89236 non-null  object
 18  limit_detail     43638 non-null  object
 19  del_yn           89236 non-null  object
 20  del_detail       16 non-null     object
dtypes: float64(4), int64(4), object(13)
memory usage: 14.3+ MB

In [5]:
data.isna().sum()

stat_nm                0
stat_id                0
chger_id               0
chger_type             0
addr                  35
lat                    0
lon                    0
use_time            7194
busi_id                0
busi_nm                0
busi_call           4709
chger_stat             0
stat_upd_dt         7942
power_type         89236
city_do_cd             0
parking_free_yn      443
stat_note          76070
limit_yn               0
limit_detail       45598
del_yn                 0
del_detail         89220
dtype: int64

In [6]:
data=data.dropna(subset=['addr'],how='any',axis=0)

In [7]:
data.isna().sum()

stat_nm                0
stat_id                0
chger_id               0
chger_type             0
addr                   0
lat                    0
lon                    0
use_time            7194
busi_id                0
busi_nm                0
busi_call           4709
chger_stat             0
stat_upd_dt         7942
power_type         89201
city_do_cd             0
parking_free_yn      443
stat_note          76035
limit_yn               0
limit_detail       45563
del_yn                 0
del_detail         89185
dtype: int64

In [8]:
data['시']=data['addr'].str.split(" ").str.get(0)

In [9]:
data['시']

0        서울특별시
1        서울특별시
2        서울특별시
3        서울특별시
4        서울특별시
         ...
89231    울산광역시
89232    울산광역시
89233    울산광역시
89234    울산광역시
89235      강원도
Name: 시, Length: 89201, dtype: object

In [10]:
data['시'].unique()

array(['서울특별시', '부산광역시', '대구광역시', '인천광역시', '광주광역시', '대전광역시', '울산광역시',
       '경기도', '강원도', '충청북도', '충청남도', '전라북도', '전라남도', '경상북도', '경상남도',
       '제주특별자치도', '세종특별자치시', '', ',', '97-32', '지상', '제일오투마트', '박연'],
      dtype=object)

In [11]:
data['시'].unique()

array(['서울특별시', '부산광역시', '대구광역시', '인천광역시', '광주광역시', '대전광역시', '울산광역시',
       '경기도', '강원도', '충청북도', '충청남도', '전라북도', '전라남도', '경상북도', '경상남도',
       '제주특별자치도', '세종특별자치시', '', ',', '97-32', '지상', '제일오투마트', '박연'],
      dtype=object)

In [12]:
data_seoul = data[data['시']=='서울특별시']
data_seoul = data_seoul[['시','stat_nm']]
data_seoul.reset_index(inplace=True,drop=True)

In [13]:
data_busan = data[data['시']=='부산광역시']
data_busan = data_busan[['시','stat_nm']]
data_busan.reset_index(inplace=True,drop=True)

In [14]:
data_daegu = data[data['시']=='대구광역시']
data_daegu = data_daegu[['시','stat_nm']]
data_daegu.reset_index(inplace=True,drop=True)

In [15]:
data_jeju = data[data['시']=='제주특별자치도']
data_jeju = data_jeju[['시','stat_nm']]
data_jeju.reset_index(inplace=True,drop=True)